version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb_git_rest
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
#    volumes:
 #     - local_pgdata:/var/lib/postgresql/data
  #      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_git_rest
    restart: always
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: twodzinski@op.pl
      PGADMIN_DEFAULT_PASSWORD: admin
 #   volumes:
  #    - pgadmin-data:/var/lib/pgadmin

#volumes:
#  local_pgdata:
#  pgadmin-data: